#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'optparse'
require 'certificate-checker'

options = {
  output: $stdout,
}

OptionParser.new do |opts|
  opts.banner = 'Usage: tls-checker [options] specification...'
  opts.version = CertificateChecker::VERSION

  opts.on('-o', '--output=FILE', 'Write to FILE') do |f|
    options[:output] = File.open(f, File::CREAT | File::APPEND | File::LOCK_EX)
  end

  opts.on('--[no-]ignore-nonexistent', 'Ignore nonexistent files and arguments') do |v|
    options[:ignore_nonexistent] = v
  end
end.parse!

factory = CertificateChecker::CertificateCheckerFactory.new(options)

ARGV.each do |arg|
  factory.certificate_checkers_for(arg).each do |checker|
    options[:output].puts checker.to_e.to_json
  end
end
